spring:
  application:
    name: configuration-service

  config:
    import: optional:configserver:${CONFIG_SERVER_HOST}:${CONFIG_SERVER_PORT}

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
