global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.0.102:8070' ]

  - job_name: 'microservices'
    eureka_sd_configs:
      - server: http://192.168.0.102:8761/eureka
    metrics_path: '/actuator/prometheus'