version: '3.1'

services:
  business-order-service:
    build:
      context: services/business-order
    image: 'krayseer/business-order-service:${APPLICATION_VERSION}'
    container_name: business-order-service

  configuration-service:
    build:
      context: services/configuration
    image: 'krayseer/configuration-service:${APPLICATION_VERSION}'
    container_name: configuration-service

  gateway:
    build:
      context: gateway
    image: 'krayseer/gateway:${APPLICATION_VERSION}'
    container_name: gateway
    ports:
      - '${GATEWAY_PORT}:${GATEWAY_PORT}'

  notification-service:
    build:
      context: services/notification
    image: 'krayseer/notification-service:${APPLICATION_VERSION}'
    container_name: notification-service

  order-service:
    build:
      context: services/order
    image: 'krayseer/order-service:${APPLICATION_VERSION}'
    container_name: order-service

  registry-service:
    build:
      context: discovery
    image: 'krayseer/discovery:${APPLICATION_VERSION}'
    container_name: registry-service
    ports:
      - '${DISCOVERY_HOST}:${DISCOVERY_PORT}'

  service-of-services:
    build:
      context: services/service
    image: 'krayseer/service-of-services:${APPLICATION_VERSION}'
    container_name: service-of-services

  statistics:
    build:
      context: services/statistics
    image: 'krayseer/statistics:${APPLICATION_VERSION}'
    container_name: statistics

  storage-service:
    build:
      context: backend/services/storage-service
    image: 'krayseer/storage-service:${APPLICATION_VERSION}'
    container_name: storage-service

  postgres:
    image: 'postgres'
    container_name: postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  keycloack:
    container_name: keycloack
    image: 'quay.io/keycloak/keycloak:24.0.2'
    ports:
      - 9098:8080
    environment:
      - KEYCLOACK_ADMIN=admin
      - KEYCLOACK_ADMIN_PASSWORD=admin
    command:
      - "start-dev"

  frontend:
    build:
      context: ui-sources/
    image: 'krayseer/splash-frontend:${APPLICATION_VERSION}'
    container_name: splash-frontend
    ports:
      - '4200:4200'