apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
      nodePort: 30070
  type: NodePort