spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_SERVER_URL}/realms/splash/protocol/openid-connect/certs

      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_SERVER_URL}/realms/splash

        registration:
          splash-admin:
            provider: keycloak
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}

server:
  port: ${GATEWAY_PORT}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Сервис заказов
        url: /api/order/v3/api-docs

      - name: Сервис автомоек
        url: /api/car-wash/v3/api-docs

      - name: Сервис обработки заказов автомойкой
        url: /api/business-order/v3/api-docs

      - name: Сервис статистики
        url: /api/statistics/v3/api-docs

      - name: Сервис уведомлений
        url: /api/notification/v3/api-docs

      - name: Сервис услуг
        url: /api/service/v3/api-docs

      - name: Сервис чатов
        url: /api/rest/chat/v3/api-docs

      - name: Сервис хранилища
        url: /api/storage/v3/api-docs

      - name: Сервис пользователей
        url: /api/user/v3/api-docs
