spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_SERVER_URL}/realms/splash/protocol/openid-connect/certs

      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_SERVER_URL}/realms/splash

        registration:
          splash-client:
            provider: keycloak
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      default-filters:
        - TokenRelay=

server:
  port: ${GATEWAY_PORT}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /order/v3/api-docs
        name: Order service

      - url: /car-wash/v3/api-docs
        name: Car wash service

      - url: /business-order/v3/api-docs
        name: Business order service

      - url: /statistics/v3/api-docs
        name: Statistics

      - url: /notification/v3/api-docs
        name: Notification service

      - url: /service/v3/api-docs
        name: Service of services
