apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configuration-service
  template:
    metadata:
      labels:
        app: configuration-service
    spec:
      containers:
        - name: configuration-service
          image: krayseer/configuration-service
          envFrom:
            - configMapRef:
                name: app-config
