apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics-service
  template:
    metadata:
      labels:
        app: statistics-service
    spec:
      containers:
        - name: statistics-service
          image: krayseer/statistics-service
          envFrom:
            - configMapRef:
                name: app-config
