apiVersion: v1
kind: Service
metadata:
  name: statistics-service
  labels:
    app: statistics-service
spec:
  selector:
    app: statistics-service
  ports:
    - protocol: TCP
      port: 8080
  type: NodePort