spring:
  application:
    name: business-order-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${BUSINESS_ORDER_SERVICE_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

#  kafka:
#    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost/realms/splash/protocol/openid-connect/certs

springdoc:
  api-docs:
    path: /business-order/v3/api-docs
  swagger-ui:
    path: /business-order/swagger-ui.html

server:
  port: 0
  error:
    include-message: always
