spring:
  application:
    name: chat-service

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_SERVER_URL}/realms/splash/protocol/openid-connect/certs

server:
  port: 0
  error:
    include-message: always
