spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${ORDER_SERVICE_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost/realms/splash/protocol/openid-connect/certs

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

#  kafka:
#    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
#    consumer:
#      group-id: orders-group
#      auto-offset-reset: earliest
#    template:
#      default-topic: topic

#springdoc:
#  api-docs:
#    path: /order/v3/api-docs
#  swagger-ui:
#    path: /order/swagger-ui.html

server:
  port: 0
  error:
    include-message: always

