apiVersion: v1
kind: Service
metadata:
  name: business-order-service
  labels:
    app: business-order-service
spec:
  selector:
    app: business-order-service
  ports:
    - protocol: TCP
      port: 8080
  type: NodePort